require("prototypes.category")
require("prototypes.equipment-grid")
require("prototypes.item")
require("prototypes.equipment")
require("prototypes.projectile")
require("prototypes.recipe")
require("prototypes.technology")