require("__OCs_base_assets__.prototypes.utils.helper")
local generator_api = require("__OCs_base_assets__.prototypes.utils.api")
-- local local_rules = require("__OCs_base_assets__.prototypes.utils.generator-tables")
-- generator_api.load_rules(local_rules)
-- require("__OCs_base_assets__.prototypes.utils.recipe-generator")

require("prototypes.category")
require("prototypes.utils.plating_variants")
require("prototypes.utils.grid_definitions") -- defines and maps categories(personal, vehicle) to equipment_grid
require("prototypes.item")
require("prototypes.equipment")
require("prototypes.equipment-grid")
require("prototypes.projectile")
require("prototypes.recipe")
require("prototypes.technology")